apiVersion: v1
kind: ConfigMap
metadata:
  name: house-price-api-config
data:
  MLFLOW_TRACKING_URI: "{{ .Values.config.mlflowTrackingUri }}"
  MLFLOW_S3_ENDPOINT_URL: "{{ .Values.config.mlflowS3EndpointUrl }}"