apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.secret.awsAccessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.secret.awsSecretAccessKey }}"