apiVersion: v1
kind: ConfigMap
metadata:
  name: house-price-api-config
data:
  MLFLOW_TRACKING_URI: "http://host.docker.internal:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://host.docker.internal:9000"